//+------------------------------------------------------------------+
//|                                              VolRegimeMatrix.mq5 |
//|                             Autogenerated Volatility Regime Base |
//+------------------------------------------------------------------+
#property copyright "Volatility Regime ML"
#property link      ""
#property version   "1.01"
#property indicator_chart_window
#property indicator_buffers 0
#property indicator_plots   0

#include <VolRegime/Types.mqh>
#include <VolRegime/FeatureEngine.mqh>
#include <VolRegime/ModelRuntime.mqh>
#include <VolRegime/DashboardUI.mqh>
#include <VolRegime/NewsCalendar.mqh>

input group "--- UI & Positioning ---"
input ENUM_VR_CORNER DashboardCorner = VR_CORNER_TOP_LEFT; // Dashboard Position
input int DashboardMarginX = 20;                           // X Margin (pixels)
input int DashboardMarginY = 40;                           // Y Margin (pixels)
input ENUM_VR_THEME DashboardTheme = VR_THEME_DARK;        // UI Color Theme

input group "--- Signal & Alerts ---"
input ENUM_VR_SENSITIVITY SignalSensitivity = VR_SENSITIVITY_STANDARD; // Signal Sensitivity
input int SignalSmoothingPeriods = 3;                                  // Signal Smoothing (1 = Off)
input bool EnableAlerts = false;                                       // Enable Volatility Alerts

VRDashboardLayout g_layout;
VRMacroContext g_macro;
datetime g_last_calc_time = 0;

double g_smoothed_vol_1h = 0.0;
double g_smoothed_vol_4h = 0.0;
double g_smoothed_tape = 0.0;
double g_smoothed_micro = 0.0;
double g_smoothed_vwap = 0.0;
bool g_is_initialized_ema = false;
bool g_was_expansive_last_tick = false;

double GetThreshold()
{
   if(SignalSensitivity == VR_SENSITIVITY_AGGRESSIVE) return 0.50;
   if(SignalSensitivity == VR_SENSITIVITY_CONSERVATIVE) return 0.65;
   return 0.55;
}

int OnInit()
{
   g_layout.panel_width = 270;
   g_layout.panel_height = 80;
   g_layout.gap = 10;
   
   if(DashboardTheme == VR_THEME_DARK)
   {
      g_layout.bg_main = C'16,20,26';
      g_layout.bg_panel = C'22,26,32';
      g_layout.border = C'55,64,74';
      g_layout.text_main = clrWhite;
      g_layout.text_dim = clrSilver;
   }
   else
   {
      g_layout.bg_main = C'240,242,245';
      g_layout.bg_panel = clrWhite;
      g_layout.border = C'200,205,210';
      g_layout.text_main = C'20,20,20';
      g_layout.text_dim = C'100,105,110';
   }
   
   // Temporary layout values until first OnTimer
   g_layout.x = DashboardMarginX;
   g_layout.y = DashboardMarginY + 30; 
   
   VRZeroMacroContext(g_macro);
   VRNewsLoadDefaultTemplate();
   
   EventSetTimer(1); // 1-second refresh for UI/tape
   return(INIT_SUCCEEDED);
}

void OnDeinit(const int reason)
{
   EventKillTimer();
   ObjectsDeleteAll(0, "VRM_");
}

int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   return(rates_total);
}

void OnTimer()
{
   datetime current_time = TimeCurrent();
   
   // Layout positioning
   int chart_w = (int)ChartGetInteger(0, CHART_WIDTH_IN_PIXELS);
   int chart_h = (int)ChartGetInteger(0, CHART_HEIGHT_IN_PIXELS);
   int total_w = (g_layout.panel_width * 2) + g_layout.gap;
   int total_h = (g_layout.panel_height * 3) + (g_layout.gap * 2) + 40;
   
   if(chart_w > 0 && chart_h > 0)
   {
      switch(DashboardCorner)
      {
         case VR_CORNER_TOP_LEFT:
            g_layout.x = DashboardMarginX;
            g_layout.y = DashboardMarginY + 30; // +30 for header
            break;
         case VR_CORNER_TOP_RIGHT:
            g_layout.x = chart_w - total_w - DashboardMarginX;
            g_layout.y = DashboardMarginY + 30;
            break;
         case VR_CORNER_BOTTOM_LEFT:
            g_layout.x = DashboardMarginX;
            g_layout.y = chart_h - total_h - DashboardMarginY + 30;
            break;
         case VR_CORNER_BOTTOM_RIGHT:
            g_layout.x = chart_w - total_w - DashboardMarginX;
            g_layout.y = chart_h - total_h - DashboardMarginY + 30;
            break;
      }
   }
   
   // Rate arrays
   MqlRates rates1m[], rates15m[], rates1h[], rates4h[];
   ArraySetAsSeries(rates1m, false);
   ArraySetAsSeries(rates15m, false);
   ArraySetAsSeries(rates1h, false);
   ArraySetAsSeries(rates4h, false);
   
   int copied_1m = CopyRates(_Symbol, PERIOD_M1, 0, 1500, rates1m);
   int copied_15m = CopyRates(_Symbol, PERIOD_M15, 0, 200, rates15m);
   int copied_1h = CopyRates(_Symbol, PERIOD_H1, 0, 200, rates1h);
   int copied_4h = CopyRates(_Symbol, PERIOD_H4, 0, 200, rates4h);
   
   if(copied_1m < 1450 || copied_15m < 120 || copied_1h < 150 || copied_4h < 150)
   {
       VRCreateOrUpdateRect(0, VRPanelName(0, "MAIN_BG"), g_layout.x - 10, g_layout.y - 30, (g_layout.panel_width * 2) + g_layout.gap + 20, (g_layout.panel_height * 3) + (g_layout.gap * 2) + 40, g_layout.bg_main, g_layout.bg_main);
       string header = _Symbol + " | SYNCHRONIZING HISTORY...";
       VRCreateOrUpdateLabel(0, VRPanelName(0, "HEADER"), g_layout.x, g_layout.y - 22, header, clrGold, 11, "Consolas Bold");
       
       string sync_text = StringFormat("M1: %d/1450 | M15: %d/120 | H1: %d/150 | H4: %d/150", 
                                       MathMax(0, copied_1m), MathMax(0, copied_15m), MathMax(0, copied_1h), MathMax(0, copied_4h));
       
       VRRenderPanel(0, g_layout, VRPanelName(0, "VOL"), g_layout.x, g_layout.y, (g_layout.panel_width * 2) + g_layout.gap, g_layout.panel_height, "Status", "Waiting for broker data...", sync_text, clrGold);
       return;
   }
   
   VRFeatureSnapshot fsnap;
   fsnap.source_time = rates1m[ArraySize(rates1m)-1].time;
   
   // Compute all feature families
   VRComputeVolFeatures(rates1h, ArraySize(rates1h), fsnap.vol_1h, g_macro, false);
   VRComputeVolFeatures(rates4h, ArraySize(rates4h), fsnap.vol_4h, g_macro, true);
   VRComputeVWAPFeatures(rates15m, ArraySize(rates15m), fsnap.vwap);
   VRComputeTapeFeatures(rates1m, ArraySize(rates1m), fsnap.tape);
   VRComputeMicroFeatures(rates1m, ArraySize(rates1m), fsnap.micro);
   
   // Propagate UI stats
   fsnap.latest_vwap_zscore   = fsnap.vwap[6];
   fsnap.latest_hurst_32      = fsnap.vwap[32];
   fsnap.latest_hurst_90      = fsnap.vol_1h[51];
   fsnap.latest_active_ratio  = fsnap.tape[8];
   fsnap.latest_silent_ratio  = fsnap.tape[9];
   fsnap.latest_tape_momentum = fsnap.tape[20];
   fsnap.latest_rsi_14        = fsnap.vol_1h[28];
   fsnap.latest_bb_pos        = fsnap.vol_1h[29];
   fsnap.latest_range_ratio   = fsnap.vwap[29];
   fsnap.latest_tickvol_accel = fsnap.vwap[30];
   fsnap.latest_rtv           = fsnap.vwap[31];
   
   // Run Inference
   VRInferenceSnapshot islap;
   VRRunInference(_Symbol, fsnap, islap);
   
   // Apply EMA Smoothing
   if(!g_is_initialized_ema)
   {
      g_smoothed_vol_1h = islap.vol_1h_prob;
      g_smoothed_vol_4h = islap.vol_4h_prob;
      g_smoothed_tape = islap.tape_prob;
      g_smoothed_micro = islap.micro_prob;
      g_smoothed_vwap = islap.vwap_prob;
      g_is_initialized_ema = true;
   }
   else
   {
      double alpha = 2.0 / (MathMax(1, SignalSmoothingPeriods) + 1.0);
      g_smoothed_vol_1h = alpha * islap.vol_1h_prob + (1 - alpha) * g_smoothed_vol_1h;
      g_smoothed_vol_4h = alpha * islap.vol_4h_prob + (1 - alpha) * g_smoothed_vol_4h;
      g_smoothed_tape = alpha * islap.tape_prob + (1 - alpha) * g_smoothed_tape;
      g_smoothed_micro = alpha * islap.micro_prob + (1 - alpha) * g_smoothed_micro;
      g_smoothed_vwap = alpha * islap.vwap_prob + (1 - alpha) * g_smoothed_vwap;
   }
   
   islap.vol_1h_prob = g_smoothed_vol_1h;
   islap.vol_4h_prob = g_smoothed_vol_4h;
   islap.tape_prob = g_smoothed_tape;
   islap.micro_prob = g_smoothed_micro;
   islap.vwap_prob = g_smoothed_vwap;
   
   double thresh = GetThreshold();
   bool is_expansive = (islap.vol_1h_prob >= thresh);
   
   // Trigger Alerts
   if(EnableAlerts && is_expansive && !g_was_expansive_last_tick)
   {
      Alert(_Symbol, " 1H Volatility Regime shifted to EXPANSIVE! (", DoubleToString(islap.vol_1h_prob * 100.0, 1), "%)");
   }
   g_was_expansive_last_tick = is_expansive;
   
   // Render
   VRNewsEvaluate(current_time, islap.news);
   VRCreateOrUpdateRect(0, VRPanelName(0, "MAIN_BG"), g_layout.x - 10, g_layout.y - 30, (g_layout.panel_width * 2) + g_layout.gap + 20, (g_layout.panel_height * 3) + (g_layout.gap * 2) + 40, g_layout.bg_main, g_layout.bg_main);
   VRRenderDashboard(0, g_layout, islap, thresh);
}
//+------------------------------------------------------------------+
